### ISSUE TITLE
Adding more tubes

### ISSUE THREAD

**Issue by sp-pinkeye** [apohl79/GuitarAmp#3]
Hi Andreas
Have been trying to use your code to build on linux and was wondering how the tube param ( go, gInf, D, H ) are obtained for each tube.
Thanks
Steve

**Comment by apohl79** [comment]
Hi Steve,

I have calculated them using a model in scilab. I think I don't have it on GitHub as it is not needed for the amp itself.

Best,
Andreas

**Comment by sp-pinkeye** [comment]
Any chance of equations ?
Have been experimenting with the tube models in Audio TK and they sound good but seems CPU hungry.

**Comment by apohl79** [comment]
The equations are defined in this thesis: http://www.hs-ulm.de/opus/frontdoor.php?source_opus=114 <http://www.hs-ulm.de/opus/frontdoor.php?source_opus=114>

I can get you the scilab files, if that helps.

**Comment by sp-pinkeye** [comment]
That would be great.
Thesis in German which makes it hard reading for me!

**Comment by apohl79** [comment]
There we go: https://gist.github.com/apohl79/429bb012fbdb97863a9c4931e6ceaa6f

**Comment by sp-pinkeye** [comment]
Great thanks, just tried to run but get this error.....new to scilab so not sure of cause...

--> exec('/home/steve/Downloads/429bb012fbdb97863a9c4931e6ceaa6f-8096be685e6912a15246b444d64fb14cf2e9e868/tube_params.sci', -1)
fsolve: exception caught in 'jac' subroutine.
at line    89 of executed file /home/steve/Downloads/429bb012fbdb97863a9c4931e6ceaa6f-8096be685e6912a15246b444d64fb14cf2e9e868/tube_params.sci

F: Wrong size for output argument #1: A matrix of size 1 x 2 expected.
--> exec('/home/steve/Downloads/429bb012fbdb97863a9c4931e6ceaa6f-8096be685e6912a15246b444d64fb14cf2e9e868/tube_params.sci', -1)
fsolve: exception caught in 'jac' subroutine.
at line    89 of executed file /home/steve/Downloads/429bb012fbdb97863a9c4931e6ceaa6f-8096be685e6912a15246b444d64fb14cf2e9e868/tube_params.sci

F: Wrong size for output argument #1: A matrix of size 1 x 2 expected.

**Comment by apohl79** [comment]
Updated the tube_params.sci in the ghist. Not sure if something changed in scilab, but the x0 vector definition required a modified syntax. Should work now.
